services:

  mysql:
    image: mysql:8.4
    container_name: security-dashboard-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: security_dashboard

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build:
      dockerfile: Dockerfile

    container_name: security-dashboard-app

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy


volumes:
  mysql-data: