spring:
  application:
    name: security-dashboard

  datasource:
    url: jdbc:mysql://mysql:3306/security_dashboard
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: debug